Create CODE_OF_CONDUCT
heybereket/oasis pull request #12
Opened 2021-03-25 05:21 UTC by Mudrank

2021-03-25 12:05 UTC, heybereket requested changes
Amazing, thank you! Left 1 piece of feedback:

2021-03-25 12:05 UTC, heybereket commented on docs/CODE_OF_CONDUCT
> +reported by contacting [heyBereket](https://twitter.com/heybereket) or [Landon](https://twitter.com/theldb_)  on Twitter ,
Could you remove Landon from here? I'm the original creator, I don't think he'd want to deal with this.

2021-03-25 12:13 UTC, heybereket commented
This seems like a copy from Ben Awad's Dogehouse, I'm going to have to decline.

2021-03-25 12:13 UTC, closed without merging

2021-03-26 06:17 UTC, Mudrank commented
>
 This seems like a copy from Ben Awad's Dogehouse, I'm going to have to decline.

Hey we use the template given by contributor-covenant.org you can check it [here](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html)